imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSION
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~

liip_test_fixtures: ~

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:
        dbname:   todo_test
        user:     root
        password:
        charset:  UTF8